# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CUGIR | HELP
email: mann-gis-l@cornell.edu
author: ""
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/cugir-help" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

timezone: America/New_York  

collections:
  help:
    output: true
    permalink: /blog/:name

defaults:
  - scope:
      path: ""
      type: help
    values:
      layout: help


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
draft_page: '/blog/drafts/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
